"""added collaborators

Revision ID: 3ee26040c371
Revises: 42c24c2d0b36
Create Date: 2023-07-23 12:46:23.148233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee26040c371'
down_revision = '42c24c2d0b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('userUID', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.create_index('ix_userinfos_tsv', [sa.text("to_tsvector('english', username)")], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_index('ix_userinfos_tsv', postgresql_using='gin')

    op.drop_table('collaborator')
    # ### end Alembic commands ###
