"""added complete date str

Revision ID: 42c24c2d0b36
Revises: 8a14828ceba5
Create Date: 2023-07-20 19:24:58.407558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c24c2d0b36'
down_revision = '8a14828ceba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed_at_time',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed_at_time',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
