"""added columns to Task

Revision ID: 43075ef65d8a
Revises: 3bc4a6bf217d
Create Date: 2023-07-20 13:30:42.830645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43075ef65d8a'
down_revision = '3bc4a6bf217d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_category_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('task_category_color', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('task_category_color')
        batch_op.drop_column('task_category_name')

    # ### end Alembic commands ###
