"""added TS Vector username

Revision ID: 7b372d70dc09
Revises: 3ee26040c371
Create Date: 2023-07-23 13:06:28.520129

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '7b372d70dc09'
down_revision = '3ee26040c371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username_tsv', sqlalchemy_utils.types.ts_vector.TSVectorType(), sa.Computed('to_tsvector(\'english\', "username")', persisted=True), nullable=True))
        batch_op.drop_index('ix_userinfos_tsv')
        batch_op.create_index('idx_userinfo_username_tsv', ['username_tsv'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_index('idx_userinfo_username_tsv', postgresql_using='gin')
        batch_op.create_index('ix_userinfos_tsv', [sa.text("to_tsvector('english'::regconfig, username)")], unique=False)
        batch_op.drop_column('username_tsv')

    # ### end Alembic commands ###
