"""added Task columns

Revision ID: b3ea111d3a8e
Revises: 7b372d70dc09
Create Date: 2023-07-25 02:20:18.863824

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b3ea111d3a8e'
down_revision = '7b372d70dc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_by', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('completed_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
